-- Goal: Find the top 5 product dimensions (category or brand) that are common to both category‑level and brand‑level profit analyses, for recent non‑autogenerated web pages, advanced‑degree customers, and a selected set of categories. The query demonstrates multiple CTEs, joins, filtering, aggregation, INTERSECT, UNION, a ranking window, and a final LIMIT.
WITH
  -- Join the four tables using the allowed foreign‑key relationships
  joined_sales AS (
    SELECT
      ws.ws_item_sk,
      ws.ws_bill_cdemo_sk,
      ws.ws_web_page_sk,
      ws.ws_ext_sales_price,
      ws.ws_net_profit,
      i.i_category,
      i.i_category_id,
      i.i_brand,
      i.i_brand_id,
      cd.cd_gender,
      cd.cd_education_status,
      wp.wp_type,
      wp.wp_autogen_flag,
      wp.wp_rec_start_date
    FROM tpcds.web_sales ws
    JOIN tpcds.item i
      ON ws.ws_item_sk = i.i_item_sk
    JOIN tpcds.customer_demographics cd
      ON ws.ws_bill_cdemo_sk = cd.cd_demo_sk
    JOIN tpcds.web_page wp
      ON ws.ws_web_page_sk = wp.wp_web_page_sk
  ),

  -- Apply at least four filter predicates
  filtered AS (
    SELECT *
    FROM joined_sales
    WHERE i_category_id IN (2, 5, 8, 9)
      AND wp_autogen_flag = 'N'
      AND wp_rec_start_date >= DATE '2000-01-01'
      AND cd_education_status = 'Advanced Degree'
  ),

  -- First aggregation: profit by category and gender
  agg_by_cat_gender AS (
    SELECT
      i_category,
      cd_gender,
      SUM(ws_ext_sales_price) AS total_sales,
      SUM(ws_net_profit) AS total_profit,
      COUNT(*) AS order_cnt
    FROM filtered
    GROUP BY i_category, cd_gender
  ),

  -- Second aggregation: profit by brand and gender
  agg_by_brand_gender AS (
    SELECT
      i_brand,
      cd_gender,
      SUM(ws_ext_sales_price) AS total_sales,
      SUM(ws_net_profit) AS total_profit,
      COUNT(*) AS order_cnt
    FROM filtered
    GROUP BY i_brand, cd_gender
  ),

  -- Intersect the key sets of the two aggregated results (category vs. brand)
  intersect_keys AS (
    SELECT i_category AS key FROM agg_by_cat_gender
    INTERSECT
    SELECT i_brand AS key FROM agg_by_brand_gender
  ),

  -- Union the two profit result sets (distinct) to force a dedup aggregation
  union_agg AS (
    SELECT i_category AS dim, total_profit FROM agg_by_cat_gender
    UNION
    SELECT i_brand AS dim, total_profit FROM agg_by_brand_gender
  ),

  -- Rank the dimensions within the intersected key set and keep the top 5 per dimension
  ranked AS (
    SELECT
      dim,
      total_profit,
      ROW_NUMBER() OVER (PARTITION BY dim ORDER BY total_profit DESC) AS rk
    FROM union_agg
    WHERE dim IN (SELECT key FROM intersect_keys)
  )

SELECT dim,
       total_profit
FROM ranked
WHERE rk <= 5
ORDER BY dim, total_profit DESC
LIMIT 100
