SELECT
    d.d_year AS return_year,
    d.d_month_seq AS return_month,
    hd_refunded.hd_buy_potential AS refunded_buy_potential,
    hd_returning.hd_buy_potential AS returning_buy_potential,
    s.s_state AS store_state,
    s.s_city AS store_city,
    wp.wp_type AS page_type,
    wp.wp_autogen_flag,
    COUNT(*) AS num_returns,
    SUM(cr.cr_net_loss) AS total_net_loss,
    SUM(cr.cr_return_amount) AS total_return_amount,
    AVG(cr.cr_fee) AS avg_fee,
    SUM(cr.cr_return_quantity) AS total_quantity,
    ROUND(AVG(cr.cr_return_amt_inc_tax), 2) AS avg_return_amt_inc_tax,
    SUM(CASE WHEN cr.cr_return_tax > 0 THEN cr.cr_return_tax ELSE 0 END) AS total_return_tax,
    COUNT(DISTINCT cr.cr_order_number) AS distinct_orders,
    CASE
        WHEN wp.wp_autogen_flag = 'Y' THEN 'AutoGenerated'
        ELSE 'Manual'
    END AS page_generation_flag,
    (SUM(cr.cr_return_amount) - SUM(cr.cr_fee)) / NULLIF(SUM(cr.cr_return_quantity), 0) AS avg_net_per_item
FROM catalog_returns cr
JOIN date_dim d
    ON cr.cr_returned_date_sk = d.d_date_sk
JOIN household_demographics hd_refunded
    ON cr.cr_refunded_hdemo_sk = hd_refunded.hd_demo_sk
JOIN household_demographics hd_returning
    ON cr.cr_returning_hdemo_sk = hd_returning.hd_demo_sk
JOIN store s
    ON s.s_closed_date_sk = d.d_date_sk
JOIN web_page wp
    ON wp.wp_creation_date_sk = d.d_date_sk
   AND wp.wp_access_date_sk = d.d_date_sk
WHERE d.d_year BETWEEN 2000 AND 2005
  AND s.s_state IS NOT NULL
  AND wp.wp_type IS NOT NULL
GROUP BY
    d.d_year,
    d.d_month_seq,
    hd_refunded.hd_buy_potential,
    hd_returning.hd_buy_potential,
    s.s_state,
    s.s_city,
    wp.wp_type,
    wp.wp_autogen_flag
ORDER BY total_net_loss DESC
LIMIT 100
