/*
  Goal: Compare total profit and sales generated by each promotion‑ship mode combination across the catalog and web channels,
  enrich the catalog side with inventory quantity on hand and customer return loss, rank the combinations by profit, and
  produce subtotals using ROLLUP. The query joins all 13 selected TPC‑DS tables following the allowed join rules,
  applies three filters (promotion channel, income band upper bound, and sold‑date range), combines two sub‑queries
  with UNION ALL, filters groups with HAVING, orders the result and limits it to the top 100 rows.
*/

WITH catalog_agg AS (
    SELECT
        p.p_promo_id               AS promo_id,
        sm.sm_ship_mode_id         AS ship_mode_id,
        SUM(cs.cs_net_profit)      AS profit,
        SUM(cs.cs_ext_sales_price) AS sales_amount,
        COALESCE(SUM(inv.inv_quantity_on_hand), 0) AS inventory_qty,
        COALESCE(SUM(sr.sr_net_loss), 0)          AS return_loss
    FROM catalog_sales cs
    JOIN promotion p               ON cs.cs_promo_sk = p.p_promo_sk
    JOIN ship_mode sm              ON cs.cs_ship_mode_sk = sm.sm_ship_mode_sk
    JOIN warehouse w               ON cs.cs_warehouse_sk = w.w_warehouse_sk
    JOIN household_demographics hd ON cs.cs_bill_hdemo_sk = hd.hd_demo_sk
    JOIN income_band ib            ON hd.hd_income_band_sk = ib.ib_income_band_sk
    JOIN customer c                ON cs.cs_bill_customer_sk = c.c_customer_sk
    LEFT JOIN inventory inv        ON inv.inv_warehouse_sk = w.w_warehouse_sk
    LEFT JOIN store_returns sr    ON sr.sr_customer_sk = c.c_customer_sk
    WHERE p.p_channel_radio = 'N'
      AND ib.ib_upper_bound > 80000
      AND cs.cs_sold_date_sk BETWEEN 2451545 AND 2451910
    GROUP BY ROLLUP (p.p_promo_id, sm.sm_ship_mode_id)
),

web_agg AS (
    SELECT
        p.p_promo_id               AS promo_id,
        sm.sm_ship_mode_id         AS ship_mode_id,
        SUM(ws.ws_net_profit)      AS profit,
        SUM(ws.ws_ext_sales_price) AS sales_amount,
        0                          AS inventory_qty,
        0                          AS return_loss
    FROM web_sales ws
    JOIN promotion p               ON ws.ws_promo_sk = p.p_promo_sk
    JOIN ship_mode sm              ON ws.ws_ship_mode_sk = sm.sm_ship_mode_sk
    JOIN warehouse w               ON ws.ws_warehouse_sk = w.w_warehouse_sk
    JOIN household_demographics hd ON ws.ws_bill_hdemo_sk = hd.hd_demo_sk
    JOIN income_band ib            ON hd.hd_income_band_sk = ib.ib_income_band_sk
    JOIN web_page wp               ON ws.ws_web_page_sk = wp.wp_web_page_sk
    JOIN web_site wsit             ON ws.ws_web_site_sk = wsit.web_site_sk
    WHERE p.p_channel_radio = 'N'
      AND ib.ib_upper_bound > 80000
      AND ws.ws_sold_date_sk BETWEEN 2451545 AND 2451910
    GROUP BY p.p_promo_id, sm.sm_ship_mode_id
)

/* Combine the two fact sources */
SELECT
    promo_id,
    ship_mode_id,
    SUM(profit)        AS total_profit,
    SUM(sales_amount)  AS total_sales,
    SUM(inventory_qty) AS total_inventory_qty,
    SUM(return_loss)   AS total_return_loss,
    RANK() OVER (ORDER BY SUM(profit) DESC) AS profit_rank
FROM (
    SELECT * FROM catalog_agg
    UNION ALL
    SELECT * FROM web_agg
) AS combined
GROUP BY ROLLUP (promo_id, ship_mode_id)
HAVING SUM(profit) > 10000
ORDER BY profit_rank, promo_id, ship_mode_id
LIMIT 100
