WITH page_dates AS (
    SELECT
        wp.wp_web_page_id,
        wp.wp_url,
        wp.wp_type,
        wp.wp_max_ad_count,
        wp.wp_char_count,
        wp.wp_link_count,
        cd.d_year AS creation_year,
        cd.d_month_seq AS creation_month_seq,
        ad.d_year AS access_year,
        ad.d_month_seq AS access_month_seq,
        CASE WHEN wp.wp_max_ad_count = 0 THEN 'NoAds' ELSE 'HasAds' END AS ad_flag
    FROM web_page wp
    JOIN date_dim cd ON wp.wp_creation_date_sk = cd.d_date_sk
    JOIN date_dim ad ON wp.wp_access_date_sk = ad.d_date_sk
    WHERE wp.wp_max_ad_count >= 1                         -- predicate 1
      AND wp.wp_type IN ('home', 'product', 'search')      -- predicate 2
      AND cd.d_year BETWEEN 1998 AND 2000                  -- predicate 3
      AND ad.d_year BETWEEN 1998 AND 2000                  -- predicate 4
      AND cd.d_holiday = 'N'                               -- predicate 5
      AND ad.d_holiday = 'N'                               -- predicate 6
),
aggregated AS (
    SELECT
        creation_year,
        wp_type,
        ad_flag,
        COUNT(DISTINCT wp_url) AS distinct_pages,
        SUM(wp_char_count)      AS total_characters,
        AVG(wp_link_count)      AS avg_links_per_page
    FROM page_dates
    GROUP BY ROLLUP (creation_year, wp_type, ad_flag)
    HAVING COUNT(DISTINCT wp_url) > 5
)
SELECT
    creation_year,
    wp_type,
    ad_flag,
    distinct_pages,
    total_characters,
    avg_links_per_page,
    RANK() OVER (PARTITION BY creation_year ORDER BY total_characters DESC) AS rank_by_characters,
    DENSE_RANK() OVER (PARTITION BY creation_year ORDER BY distinct_pages DESC) AS rank_by_page_count
FROM aggregated
WHERE creation_year IS NOT NULL   -- exclude the grand total row generated by ROLLUP
ORDER BY creation_year, rank_by_characters
