/*
  Analytical query: total discount amount generated by each promotion across all three sales channels
  (store_sales, catalog_sales, web_sales) for the calendar year 2000.
  The result is ordered by the highest total discount and limited to the top 10 promotions.
*/
WITH store_disc AS (
  SELECT
    p.p_promo_name AS promo_name,
    SUM(ss.ss_ext_discount_amt) AS discount_amount
  FROM store_sales ss
  JOIN promotion p
    ON ss.ss_promo_sk = p.p_promo_sk
  JOIN date_dim d
    ON ss.ss_sold_date_sk = d.d_date_sk
  WHERE d.d_year = 2000
  GROUP BY p.p_promo_name
),
catalog_disc AS (
  SELECT
    p.p_promo_name AS promo_name,
    SUM(cs.cs_ext_discount_amt) AS discount_amount
  FROM catalog_sales cs
  JOIN promotion p
    ON cs.cs_promo_sk = p.p_promo_sk
  JOIN date_dim d
    ON cs.cs_sold_date_sk = d.d_date_sk
  WHERE d.d_year = 2000
  GROUP BY p.p_promo_name
),
web_disc AS (
  SELECT
    p.p_promo_name AS promo_name,
    SUM(ws.ws_ext_discount_amt) AS discount_amount
  FROM web_sales ws
  JOIN promotion p
    ON ws.ws_promo_sk = p.p_promo_sk
  JOIN date_dim d
    ON ws.ws_sold_date_sk = d.d_date_sk
  WHERE d.d_year = 2000
  GROUP BY p.p_promo_name
)
SELECT
  promo_name,
  SUM(discount_amount) AS total_discount_amount
FROM (
  SELECT promo_name, discount_amount FROM store_disc
  UNION ALL
  SELECT promo_name, discount_amount FROM catalog_disc
  UNION ALL
  SELECT promo_name, discount_amount FROM web_disc
) AS all_discounts
GROUP BY promo_name
ORDER BY total_discount_amount DESC
LIMIT 10
