WITH
  -- First set: pages with returns in 2001
  returns_2001 AS (
    SELECT
      wp.wp_web_page_sk AS web_page_sk,
      wp.wp_url AS url,
      SUM(wr.wr_return_amt) AS total_return_amt
    FROM web_returns wr
    JOIN date_dim d ON wr.wr_returned_date_sk = d.d_date_sk
    JOIN web_page wp ON wr.wr_web_page_sk = wp.wp_web_page_sk
    WHERE d.d_year = 2001
    GROUP BY wp.wp_web_page_sk, wp.wp_url
  ),
  -- Second set: pages with many "Did not like" returns
  did_not_like_returns AS (
    SELECT
      wp.wp_web_page_sk AS web_page_sk,
      wp.wp_url AS url,
      SUM(wr.wr_return_amt) AS total_return_amt
    FROM web_returns wr
    JOIN web_page wp ON wr.wr_web_page_sk = wp.wp_web_page_sk
    JOIN reason r ON wr.wr_reason_sk = r.r_reason_sk
    WHERE r.r_reason_desc LIKE '%Did not like%'
    GROUP BY wp.wp_web_page_sk, wp.wp_url
  ),
  -- Union of the two sets (duplicates eliminated automatically)
  union_set AS (
    SELECT * FROM returns_2001
    UNION
    SELECT * FROM did_not_like_returns
  ),
  -- Pages that should be excluded (autogenerated pages)
  exclude_set AS (
    SELECT
      wp.wp_web_page_sk AS web_page_sk,
      wp.wp_url AS url,
      SUM(wr.wr_return_amt) AS total_return_amt
    FROM web_returns wr
    JOIN web_page wp ON wr.wr_web_page_sk = wp.wp_web_page_sk
    WHERE wp.wp_autogen_flag = 'Y'
    GROUP BY wp.wp_web_page_sk, wp.wp_url
  )
SELECT
  u.web_page_sk,
  u.url,
  u.total_return_amt,
  lt.latest_return_date
FROM union_set u
LEFT JOIN LATERAL (
  SELECT MAX(d.d_date) AS latest_return_date
  FROM web_returns wr
  JOIN date_dim d ON wr.wr_returned_date_sk = d.d_date_sk
  WHERE wr.wr_web_page_sk = u.web_page_sk
) lt ON TRUE
EXCEPT
SELECT
  e.web_page_sk,
  e.url,
  e.total_return_amt,
  NULL AS latest_return_date
FROM exclude_set e
ORDER BY total_return_amt DESC, web_page_sk
OFFSET 0 ROWS FETCH FIRST 20 ROWS ONLY
