/*
  Analytical query: For each company, show its name, location (city), region (parent place),
  the total number of comment likes generated by its employees, and the number of distinct
  universities attended by those employees. Results are ordered by total likes descending.
*/
WITH likes_per_company AS (
    SELECT
        pwc.company_id,
        SUM(COALESCE(lc.like_cnt, 0)) AS total_likes
    FROM person_work_at_company pwc
    JOIN person p ON pwc.person_id = p.id
    LEFT JOIN (
        SELECT person_id, COUNT(comment_id) AS like_cnt
        FROM person_likes_comment
        GROUP BY person_id
    ) lc ON lc.person_id = p.id
    GROUP BY pwc.company_id
),
universities_per_company AS (
    SELECT
        pwc.company_id,
        COUNT(DISTINCT psu.university_id) AS distinct_universities
    FROM person_work_at_company pwc
    JOIN person p ON pwc.person_id = p.id
    JOIN person_study_at_university psu ON psu.person_id = p.id
    GROUP BY pwc.company_id
),
company_details AS (
    SELECT
        org.id AS company_id,
        org.name AS company_name,
        pl.name AS location_name,
        parent_pl.name AS region_name
    FROM organisation org
    JOIN place pl ON org.location_place_id = pl.id
    LEFT JOIN place parent_pl ON pl.part_of_place_id = parent_pl.id
    WHERE org.type = 'Company'
)
SELECT
    cd.company_name,
    cd.location_name,
    cd.region_name,
    COALESCE(lpc.total_likes, 0) AS total_likes,
    COALESCE(upc.distinct_universities, 0) AS distinct_universities
FROM company_details cd
LEFT JOIN likes_per_company lpc ON cd.company_id = lpc.company_id
LEFT JOIN universities_per_company upc ON cd.company_id = upc.company_id
ORDER BY total_likes DESC
LIMIT 10
